### ISSUE TITLE
Conversation Follow-ups

### ISSUE THREAD

**Issue by ariv797** [symblai/symbl-python-sdk#27]
Hey! I am building a virtual assistant in python and wanted to add contextual awareness to it. For eg:-
Me: Who painted Mona Lisa
Assistant: Leonardo de Vinci
Me: When was he born?
Assistant: 1475
Can you please explain how symbl could help me in this situation? Which endpoint do I use?

**Comment by roshanijawale** [comment]
Hello!
Symbl **analyze** natural human conversation, It doesn't provide conversational flows.
If you need any help related to Symbl's API, you can join our slack community.
https://bit.ly/symbldotai-slack
